#ifndef IONE_H_
#define IONE_H_

#define SHAKE_THRESHOLD 3500
#define MOVEMENT_THRESHOLD 500
#define STILL_THRESHOLD 250

#define NUM_SHAKES_TO_TURNOFF 3
#define MINUTES_NO_MOVEMENT 2
#define ALARM_PATTERN_MAX_REPEAT 5

#define WAKE_UP 0
#define GET_UP 1
#define CALENDAR 2
#define ALARM_ON 3



#endif /* IONE_H_ */
